site_name: Aquatic Mammal Photogrammetry Tool
site_dir: documentation
theme:
  name: material
  features:
    - toc.integrate
  logo: assets/white_logo.svg
  favicon: assets/favicon-32x32.png
markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences
use_directory_urls: false
copyright: Copyright &copy; 2021 Allen Institute for Artificial Intelligence
repo_url: https://github.com/allenai/AMPT
repo_name: allenai/AMPT
edit_uri: edit/main/doc_source/docs/
plugins:
  - macros
nav:
  - Home: 'index.md'
  - 'quick_tour.md'
  - 'installation.md'
  - 'image.md'
  - 'metadata.md'
  - 'input.md'
  - 'length_and_profile.md'
  - 'csv.md'
  - 'csv_columns_config.md'
  - 'cue_and_calc.md'
  - 'config_options.md'
  - 'copyright.md'
  - 'license.md'
