name: 'Test Runner on ubuntu-latest'
on:
  workflow_dispatch:  # Allow manual triggering.
jobs:
  build_tests:
    runs-on: ubuntu-latest
    env:
      IJ_DOWNLOAD_URL: 'https://downloads.imagej.net/fiji/latest/fiji-linux64.tar.gz'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Set JAVA_HOME'
        run: |
          echo "JAVA_HOME=${JAVA_HOME_8_X64}" >> $GITHUB_ENV
      - name: 'Run All Tests'
        run: 'mvn -B test'
