name: 'Release to ImageJ update site and deploy GitHub documentation'
on:
  release:
    types: [published]
  workflow_dispatch:  # Allow manual triggering.
jobs:
  build_release:
    runs-on: 'ubuntu-latest'
    env:
      IJ_DOWNLOAD_URL: 'https://downloads.imagej.net/fiji/latest/fiji-linux64.tar.gz'
      WIKI_USER: 'ampt-dev'
      UPDATE_PASS: '${{ secrets.IMAGEJ_UPDATE_SITE_PASS }}'
      UPDATE_SITE: 'AMPT'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v2'
      - name: 'Install packages'
        run: |
          sudo apt-get update
          sudo apt-get install -y openjdk-8-jdk virtualenv
          sudo apt-get clean
      - name: 'Set JAVA_HOME'
        run: |
          echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/" >> $GITHUB_ENV
      - name: 'Run All Tests'
        run: 'mvn -B test'
